### ISSUE TITLE
Couple of bumps on the way for a new user

### ISSUE THREAD

**Issue by PeterARBork** [debbiemarkslab/EVcouplings#102]
Based on the articles, I think your method is very interesting, so I'm adding this "issue" to give something back in the form of helping you guys know where people like me get errors.

Running a pipeline nearly identical to the example_config, I ran into a long stacktrace because the lines below got a keyerror for resseq_end.

A try-catch around these with a helpful reminder instead of the long stacktrace for the std.out might be worth the effort. The reminder could be the same that the python-module has, to run without SIFT files, but only directories to recreate them.

https://github.com/debbiemarkslab/EVcouplings/blob/e35a0691bf466d3cf9edcc508ca9e2dc983f71b4/evcouplings/compare/sifts.py#L319-L321

Maybe that wouldn't solve my problem though, because after changing the config file to not have specific SIFT files, but just directories, I now get a different stacktrace for this line:
https://github.com/debbiemarkslab/EVcouplings/blob/e35a0691bf466d3cf9edcc508ca9e2dc983f71b4/evcouplings/compare/sifts.py#L235-L237

The stacktrace looks like this (paths taken out):
```
Traceback (most recent call last):
  File "./corrected_bin/evcouplings_runcfg", line 11, in <module>
    load_entry_point('evcouplings==0.0.1', 'console_scripts', 'evcouplings_runcfg')()
  File "/../venv_EVCouplings/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/../venv_EVCouplings/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/../venv_EVCouplings/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/../venv_EVCouplings/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/../evcouplings/utils/pipeline.py", line 510, in app
    outcfg = run(**kwargs)
  File "/../evcouplings/utils/pipeline.py", line 497, in run
    return execute_wrapped(**config)
  File "/../evcouplings/utils/pipeline.py", line 454, in execute_wrapped
    outcfg = execute(**config)
  File "/../evcouplings/utils/pipeline.py", line 174, in execute
    outcfg = runner(**incfg)
  File "/../evcouplings/compare/protocol.py", line 1008, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/../evcouplings/compare/protocol.py", line 485, in standard
    "prefix": aux_prefix,
  File "/../evcouplings/compare/protocol.py", line 75, in _identify_structures
    kwargs["sifts_sequence_db"]
  File "/../evcouplings/compare/sifts.py", line 236, in __init__
    sifts_table_file, comment="#"
  File "/../venv_EVCouplings/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/../venv_EVCouplings/lib/python3.6/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/../venv_EVCouplings/lib/python3.6/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/../venv_EVCouplings/lib/python3.6/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/../venv_EVCouplings/lib/python3.6/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 562, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 760, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 965, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2208, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
```

If you guys are interested in this kind of user feedback, I'll return with more next week, when I again have time to work on it. In the meantime, thanks for making the effort to make your method available.

**Comment by aggreen** [comment]
@PeterARBork - thanks for your feedback! We are definitely interested in
this sort of user input.

This might be relevant to your issue, but minimally is useful for us to
have noted: I recently did a clean installation of evcouplings in a new
conda python3 environment. I ran into an issue today where the version of
pandas that was being called by evcouplings was out of date. The complexes
pipeline failed in the compare stage on line 740 of sifts.py with a long
stacktrace - it looks like the groupby behavior has changed somewhat
between pandas versions. 'conda install pandas' fixed the problem. I'm not
sure if this is related to your earlier environment error or an issue of
our dependencies being up to date.

**Comment by thomashopf** [comment]
@PeterARBork: Certainly, much appreciated in ironing out any problems with the package! If you could provide us with the full set of input/output files (including your SIFTS tables) and both full stack traces, that would be great and very helpful to diagnose what is going wrong here. Definitely not a typical error...

@aggreen: Yep looks like a pandas issue and/or corruption of the tables to me.

Issue is possibly related to #64.

**Comment by b-schubert** [comment]
@PeterARBork:

Could you give us a bit more information. E.g. 

1) what operating system, 
2) which python version and package versions, 
3) how did you setup the virtual env, 
4) how did you install evcouplings, 
5) and lastly how did you call the pipeline

**Comment by PeterARBork** [comment]
@b-schubert:
1. OS: 14.04.1-Ubuntu
2. Python 3.6.3, tools installed in a fresh virtual environment. @aggreen: Pandas was v 0.22.0 (pip says its already up-to-date).
3. /../miniconda3/bin/python3.6 -m venv venv_EVCouplings
4. pip install evcouplings
5. /../corrected_bin/evcouplings_runcfg ./config/my_config.txt

Apart from editing my_config.txt and getting databases, the commands 3-5 is how I started the pipeline.

@thomashopf: The SIFTS tables option in the config was set to a directory which I intended to be empty, but might have had leftover files. These could perhaps have been the problem.

I will run again with clean SIFTS folders and return with full stack traces.

(PS: I only get up to one day a week on this project, so my posts here will have some latency).

**Comment by PeterARBork** [comment]
Using empty folders for the SIFTS tables in the configuration file gives me the pandas stacktrace in the original post. The code checks if the given path is a valid file, but when given an empty folder it can return a value mistaken for True:
https://github.com/debbiemarkslab/EVcouplings/blob/bf2db23ed47ff5700a4da0251a117d01fa51ce45/evcouplings/utils/system.py#L104
(I checked, and my empty folder returns value 6, which is neither None nor False).

I then tried using filepaths pointing to non-existing files, which seems to work (I get another error at the mutate step of the pipeline, as I'll detail below).

It seems the code assumes not empty directories but filepaths to files of size exactly zero.

One solution could be to have the function _create_mapping_table check if its given a filepath or directory (and generate filename), using pathlib.Path.is_file or ...is_dir, for example. Another solution is to change the text in the example config's so that it says specifically to name zero-size _file_-paths rather than directories. The latter seems easiest and would be quite sufficient for my own purpose.

**Comment by PeterARBork** [comment]
The stacktrace below is obtained as per the procedure described above.

bokeh is version 0.12.13, and a pip install --upgrade bokeh says everything is up-to-date.

I checked bokeh, and it seems they've dropped the resize tool so that I'll need an older version of bokeh to run the pipeline:
https://github.com/bokeh/bokeh/issues/4196

```
Traceback (most recent call last):
  File "corrected_bin/evcouplings_runcfg", line 11, in <module>
    load_entry_point('evcouplings==0.0.1', 'console_scripts', 'evcouplings_runcfg')()
  File "/nfs/bio/biotools/EVcouplings/venv_EVCouplings/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/bio/biotools/EVcouplings/venv_EVCouplings/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nfs/bio/biotools/EVcouplings/venv_EVCouplings/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/bio/biotools/EVcouplings/venv_EVCouplings/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nfs/bio/biotools/EVcouplings/evcouplings/utils/pipeline.py", line 510, in app
    outcfg = run(**kwargs)
  File "/nfs/bio/biotools/EVcouplings/evcouplings/utils/pipeline.py", line 497, in run
    return execute_wrapped(**config)
  File "/nfs/bio/biotools/EVcouplings/evcouplings/utils/pipeline.py", line 454, in execute_wrapped
    outcfg = execute(**config)
  File "/nfs/bio/biotools/EVcouplings/evcouplings/utils/pipeline.py", line 174, in execute
    outcfg = runner(**incfg)
  File "/nfs/bio/biotools/EVcouplings/evcouplings/mutate/protocol.py", line 168, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/nfs/bio/biotools/EVcouplings/evcouplings/mutate/protocol.py", line 80, in standard
    fig = evcouplings.visualize.mutations.plot_mutation_matrix(model, engine="bokeh")
  File "/nfs/bio/biotools/EVcouplings/evcouplings/visualize/mutations.py", line 222, in plot_mutation_matrix
    **matrix_style
  File "/nfs/bio/biotools/EVcouplings/evcouplings/visualize/mutations.py", line 359, in matrix_base_bokeh
    toolbar_location="left", tools=TOOLS
  File "/nfs/bio/biotools/EVcouplings/venv_EVCouplings/lib/python3.6/site-packages/bokeh/plotting/figure.py", line 793, in figure
    return Figure(**kwargs)
  File "/nfs/bio/biotools/EVcouplings/venv_EVCouplings/lib/python3.6/site-packages/bokeh/plotting/figure.py", line 149, in __init__
    tool_objs, tool_map = _process_tools_arg(self, opts.tools)
  File "/nfs/bio/biotools/EVcouplings/venv_EVCouplings/lib/python3.6/site-packages/bokeh/plotting/helpers.py", line 525, in _process_tools_arg
    tool_obj = _tool_from_string(tool)
  File "/nfs/bio/biotools/EVcouplings/venv_EVCouplings/lib/python3.6/site-packages/bokeh/plotting/helpers.py", line 462, in _tool_from_string
    raise ValueError("unexpected tool name '%s', %s tools are %s" % (name, text, nice_join(matches)))
ValueError: unexpected tool name 'resize', similar tools are reset
```

**Comment by b-schubert** [comment]
@PeterARBork I presume that you activated the virtual environment before you installed and called EVcouplings?

**Comment by thomashopf** [comment]
Re bokeh resize: That we will definitely need to fix ... created a separate issue in #109

Re SIFTS tables:
> I then tried using filepaths pointing to non-existing files, which seems to work (I get another  error at the mutate step of the pipeline, as I'll detail below).

That is the way the comment in the config file is intended: The folder has to be there, but the file itself isn't (i.e. the name of the file specified is the file that will be created, kind of a "save as"). Alternatively the same happens if the file would be there but completely empty.

I'll clarify the comment in the config file to be more explicit, sorry for the confusion.

**Comment by PeterARBork** [comment]
@b-schubert, yes, I activated the virtual environment before installing and running EVcouplings (the stacktrace shows the virtual environment's python 3.6 being used, and I can confirm that the virtual environment was activated before installation).

@thomashopf, I appreciate your efforts and it makes sense to me that we specify the desired "save as" filename in the config rather than an empty folder.
