### ISSUE TITLE
Jobs on o2 fail, looking for a needle in the haystack

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#127]
I've gotten celery workers to submit jobs on o2, which is nice.

In theory, the jobs are submitted transparently, meaning that it doesn't matter that _actually_ I'm submitting them from the web, so really there must be a problem with my config files.

You can see all the runs I've tried by `ssh`ing into o2 and navigating to `/n/groups/marks/web/evcouplings_backend/runs`, the most recent run is `0f10e0b64a9a9a71d36635efe1bd9694`.

All jobs fail at the compare stage with the following error:

```python
Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 454, in execute_wrapped
    outcfg = execute(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 174, in execute
    outcfg = runner(**incfg)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 1022, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 528, in standard
    d_intra.to_file(outcfg["distmap_monomer"])
AttributeError: 'NoneType' object has no attribute 'to_file'
```

I also attach the config of the most recent try: 
[0f10e0b64a9a9a71d36635efe1bd9694_config.txt](https://github.com/debbiemarkslab/EVcouplings/files/1716578/0f10e0b64a9a9a71d36635efe1bd9694_config.txt)

And here is the "master" config (aka, the template on which the job config is applied to): 
[masterconfig.txt](https://github.com/debbiemarkslab/EVcouplings/files/1716581/masterconfig.txt)

I can't seem to solve this one myself and help would be *immensely appreciated*

**Comment by sacdallago** [comment]
Fixed it:

`atom_filter` in `[batch][compare]` is set to empty string instead of `None` if default is to be used. Stems from https://github.com/debbiemarkslab/EVcouplings-server-backend/blob/development/evcouplings_server/api/jobs/parsers.py#L189

To resolve: change all `""` assignations in that dict to `None`, as well as remove default value for `get(...,>here<)` such that it falls back on `None` if no match is found.
