### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#150]
In the latest develop version, there appears to be a circular dependency, that causes the `evcouplings` CLI to fail (before submitting the job).

Stack trace:

```python
Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/bin/evcouplings", line 11, in <module>
    load_entry_point('evcouplings==0.0.2', 'console_scripts', 'evcouplings')()
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/evcouplings/utils/app.py", line 22, in <module>
    from evcouplings.utils import pipeline, database
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/evcouplings/utils/pipeline.py", line 34, in <module>
    import evcouplings.couplings.protocol as cp
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/evcouplings/couplings/protocol.py", line 18, in <module>
    from evcouplings.visualize.parameters import evzoom_json
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/evcouplings/visualize/__init__.py", line 3, in <module>
    from evcouplings.visualize.mutations import *
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/evcouplings/visualize/mutations.py", line 24, in <module>
    from evcouplings.mutate.calculations import split_mutants
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/evcouplings/mutate/__init__.py", line 2, in <module>
    from evcouplings.mutate.protocol import *
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_develop/lib/python3.6/site-packages/evcouplings/mutate/protocol.py", line 17, in <module>
    from evcouplings.visualize.mutations import (
ImportError: cannot import name 'plot_mutation_matrix'
```

Is probably exactly this: https://github.com/debbiemarkslab/EVcouplings/pull/147#discussion_r173625763

:)

**Comment by aggreen** [comment]
Ugh I don't understand why it works in the Travis build and test cases but
not in production. I will look into it but if anyone knows do chime in.

**Comment by aggreen** [comment]
If we need it to work right now, the fast fix is to roll back my commits to
the mutate protocol and not care that some of the test cases are failing

**Comment by sacdallago** [comment]
@aggreen currently the problem is that on o2 the stable branch fails with no PDBs to compare to, and the develop branch fails to submit jobs due to the circular dependency.

These problems should definitely be addressed before _publishing_, and I would argue that it's better to fix them, rather than roll back (given that the `alignment_id` derives from merging complexes?)

**Comment by sacdallago** [comment]
> Alignment_id problem derives from adding the hmmsearch functionality. We
had to tweak compare/sifts/find_homologs to be able to handle both
jackhmmer and hmmsearch results.

Thanks for clarification :)

> I think it makes the most sense for me to comment out the test case that is
introducing the circular dependency, revert the mutate protocol back to the
way it was, and push those new commits so that we can have a working
version today. Then I can take the time to figure out how to solve this
issue for real without touching the actual mutate protocol.

True. I would suggest this hotfix but we address this for 0.0.3 :) thanks!!
