### ISSUE TITLE
ValueError: HMMER added identifier prefixes to alignment because of non-unique sequence identifiers

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#189]
Ref: #175 #151

A job for [alpha-synuclein](https://www.uniprot.org/uniprot/P37840) failed on compare with the following log:

```
Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 389, in execute_wrapped
    outcfg = execute(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 185, in execute
    outcfg = runner(**incfg)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 1044, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 500, in standard
    "prefix": aux_prefix,
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 102, in _identify_structures
    **kwargs
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/sifts.py", line 723, in by_alignment
    **kwargs
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/sifts.py", line 172, in find_homologs
    ali = Alignment.from_file(a, "stockholm")
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/align/alignment.py", line 648, in from_file
    raise_hmmer_prefixes=raise_hmmer_prefixes
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/align/alignment.py", line 176, in read_stockholm
    "HMMER added identifier prefixes to alignment because of non-unique "
ValueError: HMMER added identifier prefixes to alignment because of non-unique sequence identifiers. Either some sequence identifier is present twice in the sequence database, or your target sequence identifier is the same as an identifier in the database. In the first case, please fix your sequence database. In the second case, please choose a different sequence identifier for your target sequence that does not overlap with the sequence database.
```

This is different from the issues reported above, but seems related.

It is worth mentioning that this is running from the branch of #166 , which if I'm not mistaken doesn't include the changes of #180 

I'll try to merge the latest develop into Management and run this again. Maybe @thomashopf you immediately see what happens and can deny/confirm that that's the issue.

**Comment by thomashopf** [comment]
This is the more informative error message I added as part of the solution to #175 so this appears to be in your code already.

My guess is that you are still using outdated SIFTS database files that were made with a version that doesn't have the fix (in the fixed version, the sequences in the FASTA file are prefixed with >evsp and >evtr instead of >sp and >tr to avoid the identifier clashes).

if you remake these using the most recent develop or master branch version, the problem should be gone.

**Comment by sacdallago** [comment]
That's fair. Problem: currently the `.current` version of the databases on o2 points to the 06/2018 release, which is indexed `>sp` as you correctly noted:

```
lrwxrwxrwx  1 cd174 marks   67 Aug  9 11:47 pdb_chain_uniprot_plus_current.o2.csv -> /n/groups/marks/databases/SIFTS/pdb_chain_uniprot_plus_2018_6_1.csv
lrwxrwxrwx  1 cd174 marks   66 Aug  9 11:17 pdb_chain_uniprot_plus_current.o2.fa -> /n/groups/marks/databases/SIFTS/pdb_chain_uniprot_plus_2018_7_1.fa
lrwxrwxrwx  1 cd174 marks   69 Aug  9 11:21 pdb_chain_uniprot_plus_current.o2.fasta -> /n/groups/marks/databases/SIFTS/pdb_chain_uniprot_plus_2018_6_1.fasta
```

there are later versions on o2, but they are broken:

```
[cd174@login03 SIFTS]$ more pdb_chain_uniprot_plus_2018_9_1.fasta
<!DOCTYPE html SYSTEM "about:legacy-compat">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head><title>Retrieve/ID mapping</title><meta content="IE=edge" http-equiv="X-UA-Compatible"/><meta content="text/html; charset=UTF-8" http-equiv="Content-Typ
e"/><meta content="width=device-width, initial-scale=1" name="viewport"/><link href="/" rel="home"/><link href="http://creativecommons.org/licenses/by-nd/3.0/" rel="license"/><link type="image/vnd.microsoft.icon" href="/favic
on.ico" rel="shortcut icon"/><link href="/uniprot.min.css2018_07" type="text/css" rel="stylesheet"/><script type="text/javascript">
			var BASE = '/';
			var isInternal = false;
		</script><script src="/scripts/frontier/d3/d3.v3.min.js" type="text/javascript"></script><script src="/js-compr.js2018_07" type="text/javascript"></script><script type="text/javascript">
				uniprot.namespace = 'uniprot';
				onRdyFn(function(){
					if (false) {
						var shouldShowBasket = true;
						switch(uniprot.namespace) {
....
```

I supposed the `db_update` script needs to be re-written. Apart from being moved to o2's CRON vs. orchestra. This ties in with https://github.com/debbiemarkslab/EVcouplings/issues/179 and https://github.com/debbiemarkslab/EVcouplings/issues/178 .

Pinging: @b-schubert @aggreen

** This needs fixing ASAP because about 50% of the runs that I see being submitted via web fail at this stage. **

**Comment by sacdallago** [comment]
Plan:

### High prio
- [ ] Update stable&unstable conda envs on o2
- [ ] Manually update dbs on o2 and create new symlinks for `.currents`
### medium prio
- [ ] Figure out which env is used for the monthly update and where it is being made
- [ ] Move the monthly update to o2 (vs. orchestra)

**Comment by sacdallago** [comment]
Update : I've mistakenly committed directly to develop, but it's a super small update, see https://github.com/debbiemarkslab/EVcouplings/commit/1f9f35d14570b2d19812f2f8439ac8461f9ec11d

**Comment by sacdallago** [comment]
This is now done. If this problem persist, I'll re-open.

**Comment by sacdallago** [comment]
Seems like this is still a problem?

```
Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 389, in execute_wrapped
    outcfg = execute(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 185, in execute
    outcfg = runner(**incfg)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/align/protocol.py", line 1673, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/align/protocol.py", line 1471, in standard
    ali_raw = Alignment.from_file(a, "stockholm")
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/align/alignment.py", line 648, in from_file
    raise_hmmer_prefixes=raise_hmmer_prefixes
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/align/alignment.py", line 176, in read_stockholm
    "HMMER added identifier prefixes to alignment because of non-unique "
ValueError: HMMER added identifier prefixes to alignment because of non-unique sequence identifiers. Either some sequence identifier is present twice in the sequence database, or your target seq
uence identifier is the same as an identifier in the database. In the first case, please fix your sequence database. In the second case, please choose a different sequence identifier for your ta
rget sequence that does not overlap with the sequence database.
```

just for one threshold (two other ones went through, so maybe it's just a problem in the SIFTs file?) in a web submitted job. See `/n/scratch2/d0aa2114a3501fe4cac5724db04eefed`, file: `d0aa2114a3501fe4cac5724db04eefed_b0.4.failed`.

Using all the `.current` databases and the latest version from this repo... So, I don't know :(

**Comment by thomashopf** [comment]
Nope if you check the stack trace this happens in the align stage. Reason is that a full Uniprot identifier (like sp|P01112|RASH_HUMAN) is searched against Uniprot and the region of the hit is exactly that of the query which triggers the HMMER renumbering. 

I mentioned this problem and the solution in the original issue https://github.com/debbiemarkslab/EVcouplings/issues/175#issuecomment-399681114 - fixing the identifier on the server is one line of code vs. introducing massive ugliness in the pipeline, so this one is on the server.
