### ISSUE TITLE
Name 'probability' is not defined in couplings

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#191]
Running a job using the couplings `mean_field` protocol will result in an error (previously #190, now that is amended). Here's the [config.txt](https://github.com/debbiemarkslab/EVcouplings/files/2508023/config.txt).

The output of the `.failed` file:
```
Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/scope.py", line 181, in resolve
    return self.resolvers[key]
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/collections/__init__.py", line 881, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/collections/__init__.py", line 873, in __missing__
    raise KeyError(key)
KeyError: 'probability'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/scope.py", line 192, in resolve
    return self.temps[key]
KeyError: 'probability'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 389, in execute_wrapped
    outcfg = execute(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 185, in execute
    outcfg = runner(**incfg)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 1044, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 631, in standard
    ec_table, d_intra, d_multimer, **kwargs
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 208, in _make_contact_maps
    ec_set = ecs_longrange.query("probability >= @c")
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/frame.py", line 2847, in query
    res = self.eval(expr, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/frame.py", line 2962, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/eval.py", line 291, in eval
    truediv=truediv)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 739, in __init__
    self.terms = self.parse()
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 756, in parse
    return self._visitor.visit(self.expr)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 321, in visit
    return visitor(node, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 327, in visit_Module
    return self.visit(expr, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 321, in visit
    return visitor(node, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 330, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 321, in visit
    return visitor(node, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 656, in visit_Compare
    return self.visit(binop)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 321, in visit
    return visitor(node, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 425, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 362, in _maybe_transform_eq_ne
    left = self.visit(node.left, side='left')
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 321, in visit
    return visitor(node, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/expr.py", line 439, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/ops.py", line 58, in __init__
    self._value = self._resolve_name()
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/ops.py", line 75, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/pandas/core/computation/scope.py", line 194, in resolve
    raise compu.ops.UndefinedVariableError(key, is_local)
pandas.core.computation.ops.UndefinedVariableError: name 'probability' is not defined
```

I assume that a later computational step assumes the `probability` column be present in a generated file/pandas, but `mean_field` won't produce this column as the pipeline expects, resulting in this failure. Maybe, on the other hand, it's just another required parameter missing? The latter seems unlikely.

Pinging @thomashopf @aggreen @sophiamersmann and @b-schubert to figure out if this is an actual bug (in which case: high prio) or just a missing param (in which case: not that high prio).

**Comment by sacdallago** [comment]
Upon inspection, [this seems to be the faulty line](https://github.com/debbiemarkslab/EVcouplings/blob/develop/evcouplings/compare/protocol.py#L208) and that code, according to the header, was produced by @aggreen , so maybe let's talk about it tomorrow? :) But good to know...

**Comment by sacdallago** [comment]
Personally, my experience with "overflowing" parameters is that the pipeline is going to ignore them. For example, if you were to define the `pseudo_count` but using the `standard` protocol, that parameter would just be ignored.

My guess would be that, at the same `if` statement where the presence of `plot_probability_cutoffs` gets checked, you also check what protocol you are running, and if the protocol != standard, then you will remove the `plot_probability_cutoffs` from the outconfig all together. Or something in that fashion.

The risk that I see using other approaches (but I have not thought them all through) is that you have to implement an exclusion logic in the config. Right now, there only seems to be an inclusion logic. E.g.: IF `protocol` is `mean_field`, define `pseudo_count` vs IF `protocol` is `mean_field`, define `pseudo_count` AND remove `plot_probability_cutoffs`

**Comment by thomashopf** [comment]
Bug... the fix is to add the following in https://github.com/debbiemarkslab/EVcouplings/blob/develop/evcouplings/couplings/protocol.py#L627:

```python
ecs.loc[:, "probability"] = np.nan
```

As Anna noted, we can't score the DI scores of mean-field with any of our mixture models since the score distributions look very different. But the probability column is a required default in the coupling scores table, so in this case we go for missing value (any downstream code querying on this column will get empty dataframes, which the code should handle).

Independent of this bug, also note that the user is responsible for _exchanging_ the configuration of a stage when changing to a different protocol, like here: https://github.com/debbiemarkslab/EVcouplings/blob/674d1d0fba1a30f829ec2416c7418670decbde86/config/sample_config_monomer.txt#L126

@aggreen For this reason I would very much prefer if we present the parameters for the mean-field protocol in the same way (fully specified and commented out rather than putting one additional parameter), just like for the "existing" protocol in align.

**Comment by aggreen** [comment]
I have implemented the change suggested by Thomas and am running a test all the way through the pipeline to make sure we have no other errors in the fold or mutate stage, pull request coming soon
