### ISSUE TITLE
Trying to compile an impossible URL

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#194]
When submitting a complex job via evcouplings.org, I run into the following `.failed`:

```
Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/li
b/python3.5/site-packages/evcouplings/utils/pipeline.py", line 389, in execute_w
rapped
    outcfg = execute(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/li
b/python3.5/site-packages/evcouplings/utils/pipeline.py", line 185, in execute
    outcfg = runner(**incfg)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/li
b/python3.5/site-packages/evcouplings/compare/protocol.py", line 1044, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/li
b/python3.5/site-packages/evcouplings/compare/protocol.py", line 755, in complex
    outcfg, first_sifts_map = _identify_monomer_structures("first", outcfg, firs
t_aux_prefix)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/li
b/python3.5/site-packages/evcouplings/compare/protocol.py", line 741, in _identi
fy_monomer_structures
    prefix=aux_prefix
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/li
b/python3.5/site-packages/evcouplings/compare/protocol.py", line 102, in _identi
fy_structures
    **kwargs
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/li
b/python3.5/site-packages/evcouplings/compare/sifts.py", line 760, in by_alignme
nt
    **kwargs
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/li
b/python3.5/site-packages/evcouplings/compare/sifts.py", line 169, in find_homol
ogs
    ar = jackhmmer_search(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/li
[cd174@login06 0507c25b15ede6ed625b05261cf930da]$ cat 0507c25b15ede6ed625b05261cf930da.failed
Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 389, in execute_wrapped
    outcfg = execute(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 185, in execute
    outcfg = runner(**incfg)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 1044, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 755, in complex
    outcfg, first_sifts_map = _identify_monomer_structures("first", outcfg, first_aux_prefix)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 741, in _identify_monomer_structures
    prefix=aux_prefix
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 102, in _identify_structures
    **kwargs
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/sifts.py", line 760, in by_alignment
    **kwargs
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/sifts.py", line 169, in find_homologs
    ar = jackhmmer_search(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/align/protocol.py", line 1049, in jackhmmer_search
    full_sequence_file
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/align/protocol.py", line 211, in fetch_sequence
    allow_redirects=True
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/system.py", line 267, in get
    r.status_code, url
evcouplings.utils.system.ResourceError: Invalid status code (404) for URL: http://www.uniprot.org/uniprot/sp|P12345|AATM_RABIT.fasta
```

The config (-management) is attached here: 
[conf.txt](https://github.com/debbiemarkslab/EVcouplings/files/2605269/conf.txt)

This is odd, because if I pass such an identifier in the `monomer` pipeline, it runs though just okay (e.g.: another job [conf2.txt](https://github.com/debbiemarkslab/EVcouplings/files/2605275/conf2.txt)). I assume in the complex pipeline there's a disassembly of the identifier missing?

Needs digging.

**Comment by sacdallago** [comment]
Note: the interesting part in the config is `sequence_id `. Never mind that I'm running a complex job using the same protein but different regions, just testing.

**Comment by thomashopf** [comment]
Well quite simply because `sp|P12345|AATM_RABIT` is not a valid sequence identifier. P12345 or AATM_RABIT are.

In conf2.txt, the `sequence_file` is passed into the compare stage via global (plus it feeds out of the align stage as an output), so the pipeline doesn't go out and fetch from Uniprot in compare and therefore your problem doesn't surface.

@aggreen: Can you please check why the sequence files from the two align stages don't make it into the compare stage in the complex pipeline? This probably is the reason why the wrong identifier input surfaced as a crash in compare.

**Comment by aggreen** [comment]
Hey all - 

@thomashopf I have verified by looking at my test cases and the code traceback that the sequence_file kwarg from both monomer alignment stages are passed through to compare correctly as first_sequence_file and second_sequence_file, respectively

@sacdallago you are correct that this line is causing the problem, but I'm worried about your input configuration. The kwarg sequence_file is not produced in the concatenate stage nor is it present in my .incfg files to the compare stage.  I wonder if you are calling some stage incorrectly and it is producing stray kwargs - are you able to track where this came from?

**Comment by thomashopf** [comment]
Okay, so it looks like the root cause is https://github.com/debbiemarkslab/EVcouplings/blob/master/config/sample_config_complex.txt#L372 which clearly should be `first_sequence_file`, not `sequence_file`.

This null value from the inconfig then presumably overwrites the prefix-reduced `first_sequence_file` in the dictionary comprehension in https://github.com/debbiemarkslab/EVcouplings/blob/develop/evcouplings/compare/protocol.py#L731, triggering the sequence fetching.

1. Immediate fix: correct the config file https://github.com/debbiemarkslab/EVcouplings/blob/master/config/sample_config_complex.txt#L372 to `first_sequence_file` and the problem should be gone.

2. We may want to make the dictionary subsitution (https://github.com/debbiemarkslab/EVcouplings/blob/develop/evcouplings/compare/protocol.py#L731) more robust, making sure the prefix-reduced items always overwrite the other items as @sacdallago suggests. But only as a failsafe, this is not a substitution behaviour we should make intentional use of.


Re webserver backend: Would be clearer to use the Uniprot accession number/sequence name only, not the composite. Not sure why I had it that way.

**Comment by sacdallago** [comment]
Just FYI I've implemented the quick fix in the default complex config. @aggreen will you look into the refactoring of that one line into a function?
