### ISSUE TITLE
Pipeline fails at producing visualizations

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#212]
From a web submitted run (see `/n/groups/marks/web/backend/runs/7cbb0143a58e83b4b1373af43408d85d`):

```
Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 389, in execute_wrapped
    outcfg = execute(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 185, in execute
    outcfg = runner(**incfg)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 1044, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 1001, in complex
    second_segment_name, **kwargs
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 377, in _make_complex_contact_maps
    output_file=output_file
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/compare/protocol.py", line 318, in plot_complex_cm
    scale_sizes=kwargs["scale_sizes"]
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/visualize/pairs.py", line 488, in complex_contact_map
    multimer=d_multimer_i, **new_kwargs
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/visualize/pairs.py", line 337, in plot_contact_map
    style=scale_func(secstruct_style), ax=ax
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/visualize/pairs.py", line 842, in plot_secondary_structure
    start_i, end_i, segments_i = _extract_secstruct(secstruct_i, x_range)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/visualize/pairs.py", line 811, in _extract_secstruct
    first_pos, last_pos = min(secstruct), max(secstruct) + 1
ValueError: min() arg is an empty sequence
```

Also see: https://evcouplings.org/jobs/7cbb0143a58e83b4b1373af43408d85d (this link is only valid for 6d)

**Comment by aggreen** [comment]
So, looks like the code is failing when it tries to draw a secondary structure that doesn't exist, because it can't find appropriate boundaries. I'm not sure why I haven't gotten this error before in my pipeline runs. I can look into why this is happening and adding better checking for empty sequences in a couple weeks. 

The easy temporary fix for this is to just change the draw_secondary_structure parameter to false for the complex runs, I think that should eliminate all the issues.

**Comment by sacdallago** [comment]
Thanks @aggreen . This parameter has now been changed on the template for the web jobs.

**Comment by aggreen** [comment]
Can we resubmit the offending run just to be sure the fix worked? We should
only need to rerun the compare stage

**Comment by sacdallago** [comment]
@aggreen was also thinking about that. Will do later.

also: I've checked all failed jobs, and this issue affected 4 jobs

**Comment by sacdallago** [comment]
Update: job is now running with the changed parameter. Check results at `/n/groups/marks/users/cd/evcouplings_webserver_manual_runs/7cbb0143a58e83b4b1373af43408d85d`
