### ISSUE TITLE
[COMPLEX] evcouplings.utils.config.InvalidParameterError: provided annotation file 7a74f5bd34b11f505e287d1fd767fbf9/align_1/7a74f5bd34b11f505e287d1fd767fbf9_annotation.csv has no annotation information

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#214]
```
Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 389, in execute_wrapped
    outcfg = execute(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/utils/pipeline.py", line 185, in execute
    outcfg = runner(**incfg)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/complex/protocol.py", line 576, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/complex/protocol.py", line 454, in best_hit
    kwargs["paralog_identity_threshold"]
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/complex/protocol.py", line 427, in _load_monomer_info
    annotation_table = read_species_annotation_table(annotations_file)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_backend_develop/lib/python3.5/site-packages/evcouplings/complex/similarity.py", line 61, in read_species_annotation_table
    annotation_file
evcouplings.utils.config.InvalidParameterError: provided annotation file 7a74f5bd34b11f505e287d1fd767fbf9/align_1/7a74f5bd34b11f505e287d1fd767fbf9_annotation.csv has no annotation information
```

One job failed with this error:
`/n/groups/marks/web/backend/runs/7a74f5bd34b11f505e287d1fd767fbf9 `

**Comment by aggreen** [comment]
This is not a bug, it's an error message I put in deliberately to flag when the user's annotation file doesn't have any annotation information. I'm guessing either they aligned against a weird database, uploaded their own alignment and didn't provide any annotation information, or they aligned against uniref/uniprot and didn't find any hits. We may want to think of better ways to communicate this to the user, but ultimately their job has failed because their sequences had no species information that could extract.

**Comment by sacdallago** [comment]
Ok.

Thy aligned against uniref100 using the pipeline (upload of alignments is not yet possible), so most likely the second case (didn't find any hits). I tried to blast one of the two sequences and indeed I got very ridiculous hits. So this is an accepted failure? Think it would qualify as something to add to the FAQ on the website...

[config.txt](https://github.com/debbiemarkslab/EVcouplings/files/3038394/config.txt)
[fasta.txt](https://github.com/debbiemarkslab/EVcouplings/files/3038395/fasta.txt)

**Comment by sacdallago** [comment]
P.S.: Yes, maybe a more explicative error message in the pipeline would be great?
