### ISSUE TITLE
Deprecated usage of pandas's "loc"

### ISSUE THREAD

**Issue by nrollins-Ag** [debbiemarkslab/EVcouplings#231]
When computing couplings from an existing alignment .sto file, error can be thrown:
```Traceback (most recent call last):
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/evcouplings/utils/pipeline.py", line 456, in execute_wrapped
    outcfg = execute(**config)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/evcouplings/utils/pipeline.py", line 176, in execute
    outcfg = runner(**incfg)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/evcouplings/align/protocol.py", line 1673, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/evcouplings/align/protocol.py", line 695, in existing
    ali_raw, from_annotation=from_anno_line
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/evcouplings/align/protocol.py", line 465, in extract_header_annotation
    return df.loc[:, ["id", "name"] + list(col_to_descr.keys())]
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/pandas/core/indexing.py", line 1761, in __getitem__
    return self._getitem_tuple(key)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/pandas/core/indexing.py", line 1288, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/pandas/core/indexing.py", line 1953, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/pandas/core/indexing.py", line 1594, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/pandas/core/indexing.py", line 1552, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/n/groups/marks/software/anaconda_o2/envs/evcouplings_stable/lib/python3.6/site-packages/pandas/core/indexing.py", line 1654, in _validate_read_indexer
    "Passing list-likes to .loc or [] with any missing labels "
KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'
```

I believe this is happening because the pipeline is collecting certain columns of a pandas dataframe made from the annotations- but they are absent. As of an update, pandas will error when this happens instead of populating NaNs. Their recommended solution is to replace use of ".loc" with ".reindex" when collecting possibly absent entries / columns / rows.

**Comment by thomashopf** [comment]
Yep that has been there quite for a long time now... solution is indeed using reindex

**Comment by thomashopf** [comment]
Fixed - branch that has this update will be pushed & merged in near future

**Comment by kpgbrock** [comment]
Hi all, has this branch been merged and pushed to our cluster? Labmate ran into this issue as well. Let me know how I can help!

**Comment by thomashopf** [comment]
Fixed now in develop branch - will write by email about updates on o2
