### ISSUE TITLE
PLMC Tool Error

### ISSUE THREAD

**Issue by cross12tamu** [debbiemarkslab/EVcouplings#238]
Hey y'all, hope you're doing well.
Below is an error from running a monomer job. 

Let me know what you think I should do next, or simply if this is a "strike it up with PLMC" type error.

Thanks as always for your time and brain energy!

```
Traceback (most recent call last):
  File "run_ev.py", line 7, in <module>
    outcfg = execute(**config)
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 176, in execute
    outcfg = runner(**incfg)
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/couplings/protocol.py", line 801, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/couplings/protocol.py", line 297, in standard
    outcfg, ecs, segments = infer_plmc(**kwargs)
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/couplings/protocol.py", line 214, in infer_plmc
    binary=kwargs["plmc"],
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/couplings/tools.py", line 275, in run_plmc
    cmd, return_code, stdout, stderr
evcouplings.utils.system.ExternalToolError: Call failed:
cmd=['/home/curtisross/research/ext-tools/plmc/bin/plmc', '-c', '/home/curtisross/research/cpt-aux/protein-covariance/N4/results/monomer/gp53-LINregulator-default/couplings/gp53-LINregulator-default_ECs.txt', '-o', '/home/curtisross/research/cpt-aux/protein-covariance/N4/results/monomer/gp53-LINregulator-default/couplings/gp53-LINregulator-default.model', '-f', 'gp53-LINregulator', '-g', '-m', '100', '-t', '0.19999999999999996', '-lh', '0.01', '-le', '621.6800000000001', '/home/curtisross/research/cpt-aux/protein-covariance/N4/results/monomer/gp53-LINregulator-default/align/gp53-LINregulator-default.a2m']
returncode=-9
stdout=
stderr=Found focus gp53-LINregulator as sequence 1
43 valid sequences out of 43 
3273 sites out of 3500
Region starts at 1
Effective number of samples: 22.0	(80% identical neighborhood = 1.000 samples)
```

**Comment by thomashopf** [comment]
Hi @cross12tamu 

I think what happens here is that your computer simply runs out of RAM because the model is so large (>3000 sites).

The better approach here is to select sub-regions for the target protein and run EVcouplings for those. Also, with a model that large and 22 effective sequences, it is impossible to get meaningful results, so that is another reason to look at smaller sub-regions of your target.

Hope that helps!

**Comment by cross12tamu** [comment]
That does, thanks @thomashopf !
