### ISSUE TITLE
include sample data and a working example

### ISSUE THREAD

**Issue by GodloveD** [debbiemarkslab/EVcouplings#240]
I am an HPC support scientist who has been asked to install this pipeline on a user's behalf.  I have no domain knowledge and cannot work out how to test the pipeline based on the information in the jupyter notebooks.  In particular, I think it would be great if this repo contained a small amount of sample data (or perhaps links to a place where sample data could be downloaded) and if the `align_*:` fields in the conf file already contained relative paths to these data so that the `evcouplings_batch` script worked (or nearly worked) out of the box.  This would also aid any efforts toward CI/CD testing.  Thanks!

**Comment by thomashopf** [comment]
Can you please let us know which parts you could not work out? Then we can try to clarify. We have plans to create simpler documentation and also to dockerize the application with its dependencies, but due to limited bandwidth, this will still take us a while.

To get the application up and running, it should suffice to follow the steps outlined in the main README:
1. Install Python package (best to use develop branch from github repo, which will be released as v0.0.6 very soon)
2. Download external tools and database
3. Edit sample_config_monomer.txt so it contains paths to tools and databases from step 2
4. Run the application e.g for RASH_HUMAN protein and three bitscore thresholds (0.3, 0.5, 0.7): 
```
evcouplings -p RASH_HUMAN -P prefix/to/run_output_files -b "0.3 0.5 0.7" sample_config_monomer.txt
```

**Comment by thomashopf** [comment]
Sorry, there was a slight mistake in the CLI command, it should read (commas in -b flag added):
```
evcouplings -p RASH_HUMAN -P prefix/to/run_output_files -b "0.3,0.5 0.7" sample_config_monomer.txt
```


In the end, there should be the following files indicating successful completion for each of the subjobs:
* a file ending with ".done" (job status indicator)
* a file ending with "_final.outcfg" (results summary file)
* a folder with subfolders for the different stages (align/couplings/mutate/compare/fold) with files generated during each of the stages (please see output_files_tutorial.ipynb for details)

If the job failed, there will be a file ending with ".failed", ".terminated", or ".bailout" (depending on failure type). 

We would very much appreciate help with containerizing (having a Singularity container would be great too) - would especially love to know how you handled the large database files in your setup. In the end, this probably would have to live in a separate repository since some of the external tools are GPL-licensed, so I would suggest to have a separate issue first and then we can create a separate repository as needed.

**Comment by GodloveD** [comment]
Thanks very much for the follow up @thomashopf.  Looks like the command that you copied and pasted above also gives the same error, but it pointed me in the right direction and I was able to get a little further by adding another comma between `0.5` and `0.7`.  

Now (the containerized) evcouplings is complaining because it wants to use `sbatch` directly but `sbatch` only exists on the cluster itself and not within the container.  I might be able to bind mount the appropriate directories into the container to get slurm working, but that will take some tinkering.  

As far as the containerization goes, I did not put the databases into the container.  Instead, I downloaded them to the system and then bind mounted them into the container at runtime.  I think it is usually a better approach to keep the data and the code separate like this.  I'll try to get this working with our system slurm if possible and then I'll submit a PR with the def file.

**Comment by thomashopf** [comment]
Sorry - managed to forget the second comma (again). I edited the commands in both replies above in case someone else comes across this thread.

Thanks for info on containerization - I agree it makes sense to keep the databases outside the container and separate from the code.

**Comment by GodloveD** [comment]
I've made some progress on this, but now I'm seeing the following error:
```$ cat run_output_files_b0.5.failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 456, in execute_wrapped
    outcfg = execute(**config)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 176, in execute
    outcfg = runner(**incfg)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/align/protocol.py", line 1673, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/align/protocol.py", line 1485, in standard
    annotation = extract_header_annotation(ali_raw)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/align/protocol.py", line 465, in extract_header_annotation
    return df.loc[:, ["id", "name"] + list(col_to_descr.keys())]
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1289, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1954, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1595, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1655, in _validate_read_indexer
    "Passing list-likes to .loc or [] with any missing labels "
KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'
```
Do I need to install an older version of pandas?  Can you recommend a version number?  Something else?

**Comment by thomashopf** [comment]
@GodloveD For now, please install evcouplings directly from the development branch (cf https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch). This particular issue was fixed in #231, but has not yet heen merged into the master branch or been pushed to pypi.

(Sorry about that, we really need to release a v0.0.6 very soon that has all of the more recent fixes)

**Comment by GodloveD** [comment]
Thanks for sticking with me @thomashopf.  I tried the latest develop commit and it seems to choke when I put a command in the `configuration:` field of the conf file.  In particular, I've got a command there to set the `$PATH` since evcouplings is not installed in a system directory.  When I try to do so the jobs bail with the following errors:
```
slurmstepd: error: execve(): export: No such file or directory
srun: error: node1: task 0: Exited with exit code 2
slurmstepd: error: execve(): export: No such file or directory
srun: error: node2: task 0: Exited with exit code 2
slurmstepd: error: execve(): export: No such file or directory
srun: error: node3: task 0: Exited with exit code 2
```
Seems like anything I put in the `configuration:` field results in a similar error (with the word `export` replaced by the first string).

**Comment by thomashopf** [comment]
This is actually a problem I ran into myself a while ago. I think the fundamental issue is that slurm appears to not execute the commands inside a shell but directly, hence commands like `export` not being available.

As a fix, I added an option to supply the necessary information using environment variables (these normally should get passed on by the submission environment to the slurm job).

The fix would be to set
* `EVCOUPLINGS_RUNCFG_APP` to the path of `evcouplings_runcfg` and 
* `EVCOUPLINGS_SUMMARIZE_APP` to the path of  `evcouplings_summarize`

Can you get it to work then?

**Comment by GodloveD** [comment]
Sorry for the delay and thank you for you suggestion.  This got my past that error and then I ran into some more errors that had to do with the containerized installation I think.  Now I've got a new issue:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/utils/system.py", line 68, in run
    cwd=working_dir, shell=shell, env=env
  File "/opt/conda/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/bin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/evcouplings_runcfg", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 583, in app
    outcfg = run(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 570, in run
    return execute_wrapped(**config)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 508, in execute_wrapped
    outcfg = execute(**config)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 187, in execute
    outcfg = runner(**incfg)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/fold/protocol.py", line 714, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/fold/protocol.py", line 357, in standard
    residues = secondary_structure(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/fold/protocol.py", line 117, in secondary_structure
    target_seq_file, output_dir, binary=kwargs["psipred"]
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/fold/tools.py", line 217, in run_psipred
    [binary, fasta_file], working_dir=output_dir,
  File "/opt/conda/lib/python3.7/site-packages/evcouplings/utils/system.py", line 85, in run
    ) from e
evcouplings.utils.system.ExternalToolError: Call to external tool failed and did not return: ['/some/path/repo/EVcouplings/config/out/run_output_files_b0.7/align/run_output_files_b0.7.fa']
srun: error: cn3129: task 0: Exited with exit code 1
```
It looks like the root cause of the problem is a permission error in `/usr/local/bin`?  In this case `/usr/local/bin` is inside of the container, and it is the place where I've installed all of the dependencies for evcouplings.  I've double checked that all of the executables have the world read and execute bits set.  Could the permissions error be caused by something that is trying to write to it's installation directory?  Do you usually install these tools in a place where the user had read/write access?  Thank you.

**Comment by thomashopf** [comment]
@GodloveD I can't fully exclude the possibility that psipred writes some sort of temp file in its installation directory.. 

What I am slightly confused by is the ```and did not return: ['/some/path/repo/EVcouplings/config/out/run_output_files_b0.7/align/run_output_files_b0.7.fa']```, since this does not list the path to the binary that should be called (runpsipred). Can you please post what setting for psipred you have in the tools section of your config?

Also, another user recently had trouble installing PSIPRED due to usage of relative paths - maybe worthwile checking this too: https://github.com/debbiemarkslab/EVcouplings/issues/230

**Comment by GodloveD** [comment]
Hi @thomashopf.  The `['/some/path/repo/EVcouplings/config/out/run_output_files_b0.7/align/run_output_files_b0.7.fa']` in the error is an artifact of the way in which I've containerized the program I think.  I'll have a look at the issue that you've linked and try to test `psipred` in less complicated context.

**Comment by thomashopf** [comment]
Closing due to inactivity, please reopen if necessary
