### ISSUE TITLE
KeyError: 'samples' using complex pipeline

### ISSUE THREAD

**Issue by kirannazarali** [debbiemarkslab/EVcouplings#285]
I hope you are doing well. I am trying to run the evcouplings complex pipeline using the sample_config_file by providing 2 UniProt protein ids. I also followed the instructions for the necessary installations and requirements based on the ReadMe file, and I have provided the paths to these installations in the config file. The align_1, align_2, and concatenate steps run through successfully with the appropriate output files. However, I am receiving a KeyError: 'samples' error during the couplings step. Below is the stack trace of the error. Prior to the error, _couplings.incfg and _ECs.txt were generated. I would really appreciate your help in resolving this error. Thank you!

Traceback (most recent call last):
  File "/ihome/djishnu/krn34/.local/bin/evcouplings_runcfg", line 8, in <module>
    sys.exit(app())
  File "/ihome/crc/install/python/ondemand-jupyter-python3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/ihome/crc/install/python/ondemand-jupyter-python3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/ihome/crc/install/python/ondemand-jupyter-python3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ihome/crc/install/python/ondemand-jupyter-python3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/ihome/djishnu/krn34/.local/lib/python3.8/site-packages/evcouplings/utils/pipeline.py", line 583, in app
    outcfg = run(**kwargs)
  File "/ihome/djishnu/krn34/.local/lib/python3.8/site-packages/evcouplings/utils/pipeline.py", line 570, in run
    return execute_wrapped(**config)
  File "/ihome/djishnu/krn34/.local/lib/python3.8/site-packages/evcouplings/utils/pipeline.py", line 508, in execute_wrapped
    outcfg = execute(**config)
  File "/ihome/djishnu/krn34/.local/lib/python3.8/site-packages/evcouplings/utils/pipeline.py", line 187, in execute
    outcfg = runner(**incfg)
  File "/ihome/djishnu/krn34/.local/lib/python3.8/site-packages/evcouplings/couplings/protocol.py", line 974, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/ihome/djishnu/krn34/.local/lib/python3.8/site-packages/evcouplings/couplings/protocol.py", line 521, in complex
    outcfg, ecs, segments = infer_plmc(**kwargs)
  File "/ihome/djishnu/krn34/.local/lib/python3.8/site-packages/evcouplings/couplings/protocol.py", line 203, in infer_plmc
    plmc_result = ct.run_plmc(
  File "/ihome/djishnu/krn34/.local/lib/python3.8/site-packages/evcouplings/couplings/tools.py", line 285, in run_plmc
    iter_df, out_fields = parse_plmc_log(stderr)
  File "/ihome/djishnu/krn34/.local/lib/python3.8/site-packages/evcouplings/couplings/tools.py", line 98, in parse_plmc_log
    eff_samples = float(matches["samples"][0])
KeyError: 'samples'

**Comment by Pz-Maajid** [comment]
Can you show the commands from start that you used for the installation of the EVcouplings and the command for running the job.

**Comment by kirannazarali** [comment]
Thank you for your response.

To update to the development branch evcouplings-0.1.2, I used pip install -U --no-deps https://github.com/debbiemarkslab/EVcouplings/archive/develop.zip
I also tried to run the pipeline with evcouplings 0.1.1 with pip install evcouplings, but received the same error during the couplings steps of the pipeline. 

To run the pipeline, I am using the EVcouplings/config/sample_config_complex.txt and the command evcouplings_runcfg with the config file. I have updated the tools and databases sections in the config file based on the required installations from the readMe file. In the config file, I have inputted the UniProt id of the first protein in the align_1 section in the sequence_id field and the UniProt id of the second protein in the align_2 section in the sequence_id field.

In the databases section of the config file, I have included the paths to uniref100, sifts_mapping_table, sifts_sequence_db,  uniprot_to_embl_table, and ena_genome_location_table. In the tools section of the config file, I used conda to install jackhmmer and included the path for this in the config file. I also installed plmc from the plmc github repository, used the provided command make all-openmp32, and included the path for this in the config file.

After running the pipeline, it seems that align_1, align_2, and concatenate steps successfully run. The error occurs in the couplings step. Based on the stack trace that I have included above, it appears that error is occurring from the infer_plmc() function. I would really appreciate your help in understanding and resolving this error. Thank you!
