### ISSUE TITLE
parameters for supplying external alignment file in evcouplings

### ISSUE THREAD

**Issue by Yogesh1-11** [debbiemarkslab/EVcouplings#287]
hi, 
I have been trying to supply a .aln file to evcouplings installed locally in conda environment. But i am running into parameter file errors. quick suggestions will be  really helpful

$ evcouplings config.txt
Traceback (most recent call last):
  File "/home/administrator/anaconda3/envs/evcoupling/bin/evcouplings", line 8, in <module>
    sys.exit(app())
  File "/home/administrator/anaconda3/envs/evcoupling/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/administrator/anaconda3/envs/evcoupling/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/administrator/anaconda3/envs/evcoupling/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/administrator/anaconda3/envs/evcoupling/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/administrator/anaconda3/envs/evcoupling/lib/python3.9/site-packages/evcouplings/utils/app.py", line 559, in app
    run(**kwargs)
  File "/home/administrator/anaconda3/envs/evcoupling/lib/python3.9/site-packages/evcouplings/utils/app.py", line 483, in run
    run_jobs(
  File "/home/administrator/anaconda3/envs/evcoupling/lib/python3.9/site-packages/evcouplings/utils/app.py", line 311, in run_jobs
    raise InvalidParameterError(
evcouplings.utils.config.InvalidParameterError: Existing configuration file lsi1_out_config.txt indicates current prefix lsi1_out would overwrite existing results. Use --yolo flag to deactivate overwrite protection (e.g. for restarting a job or running a different stage).
 
my config file is.

pipeline: protein_monomer
stages:
- align
- couplings
global:
  cpu: 1
  theta: 0.8
  prefix: out
  sequence_id: aaaaa
  sequence_file: bbb.fasta
align:
  protocol: existing
  input_alignment: ccc.aln
  first_index: 1
  minimum_sequence_coverage: 50
  minimum_column_coverage: 70
couplings:
  focus_mode: true
  ignore_gaps: true
  iterations: 100
  lambda_J: 0.01
  lambda_J_times_Lq: true
  lambda_h: 0.01
  min_sequence_distance: 6
  protocol: standard
  reuse_ecs: true
  scoring_model: skewnormal 
environment:
  engine: local
  queue:
  cores: 1
  memory:
  time:
  configuration:
tools:
  jackhmmer: /home/administrator/anaconda3/envs/evcoupling/bin/jackhmmer
  plmc: /home/administrator/aaa/plmc-master/bin/plmc

**Comment by thomashopf** [comment]
This is due to executing a run that would overwrite previous results, as specified in the error message - please use --yolo flag to overwrite or delete previous run outputs before rerunning.
