### ISSUE TITLE
ResourceError when running evcouplings_dbupdate

### ISSUE THREAD

**Issue by MarioAsti8** [debbiemarkslab/EVcouplings#304]
Hi. I am getting a ResourceError with uniprot when trying to run evcouplings_dbupdate:

/home/mario/miniconda3/envs/pydca/lib/python3.6/site-packages/click/core.py:754: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  return __callback(*args, **kwargs)
Traceback (most recent call last):
  File "/home/mario/miniconda3/envs/pydca/bin/evcouplings_dbupdate", line 8, in <module>
    sys.exit(app())
  File "/home/mario/miniconda3/envs/pydca/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mario/miniconda3/envs/pydca/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mario/miniconda3/envs/pydca/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mario/miniconda3/envs/pydca/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mario/miniconda3/envs/pydca/lib/python3.6/site-packages/evcouplings/utils/update_database.py", line 189, in app
    run(**kwargs)
  File "/home/mario/miniconda3/envs/pydca/lib/python3.6/site-packages/evcouplings/utils/update_database.py", line 132, in run
    s_new.create_sequence_file(sifts.format(year=year, month=month, day=day, extension="fasta"))
  File "/home/mario/miniconda3/envs/pydca/lib/python3.6/site-packages/evcouplings/compare/sifts.py", line 448, in create_sequence_file
    seqs = fetch_uniprot_mapping(ch)
  File "/home/mario/miniconda3/envs/pydca/lib/python3.6/site-packages/evcouplings/compare/sifts.py", line 107, in fetch_uniprot_mapping
    r.status_code, url
evcouplings.utils.system.ResourceError: Invalid status code (405) for URL: https://www.uniprot.org/mapping/

It seems that https://www.uniprot.org/mapping/ does not exist. What would be the current web source? Thanks!

**Comment by hermannschwaerzlerUIBK** [comment]
Hi @MarioAsti8,

I had the very same problem. I was able to solve by installing the development-version of EVcouplings as this problem was fixed some time ago (see commit https://github.com/debbiemarkslab/EVcouplings/commit/a50bd0f00914076c7027a471d496d73cb582a24b) but this fix is not included in the release-version as that one is quite old.

**Comment by MarioAsti8** [comment]
Hi @hermannschwaerzlerUIBK ,

It looks like it worked, thanks! But it has been running for about 17 hours now, should it be taking this long? I have a .fasta and .csv file in the SIFTS directory and a .fasta in the uniprot directory. How long should it be taking? Thanks!

**Comment by thomashopf** [comment]
Yes unfortunately generating the fasta file can take a lot of time depending how busy the UniProt API is. 

The SIFTS generation code is now up-to-date on the pip-installable version as well: closing for now but please reopen if you encounter any issues.
