### ISSUE TITLE
raise ExternalToolError(evcouplings.utils.system.ExternalToolError: Call failed)

### ISSUE THREAD

**Issue by mtopolska** [debbiemarkslab/EVcouplings#305]
Hi, I have been running EVcouplings (just the align stage) for a larger set of short protein domains (50-80aa) and a small subset of those end with an error as follows:

```
Traceback (most recent call last):
  File "/users/blehner/mtopolska/miniconda3/envs/EVcouplings/lib/python3.11/site-packages/evcouplings/utils/pipeline.py", line 508, in execute_wrapped
    outcfg = execute(**config)
             ^^^^^^^^^^^^^^^^^
  File "/users/blehner/mtopolska/miniconda3/envs/EVcouplings/lib/python3.11/site-packages/evcouplings/utils/pipeline.py", line 187, in execute
    outcfg = runner(**incfg)
             ^^^^^^^^^^^^^^^
  File "/users/blehner/mtopolska/miniconda3/envs/EVcouplings/lib/python3.11/site-packages/evcouplings/align/protocol.py", line 1708, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/blehner/mtopolska/miniconda3/envs/EVcouplings/lib/python3.11/site-packages/evcouplings/align/protocol.py", line 1489, in standard
    jackhmmer_outcfg = jackhmmer_search(**kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/blehner/mtopolska/miniconda3/envs/EVcouplings/lib/python3.11/site-packages/evcouplings/align/protocol.py", line 1116, in jackhmmer_search
    ali = at.run_jackhmmer(
          ^^^^^^^^^^^^^^^^^
  File "/users/blehner/mtopolska/miniconda3/envs/EVcouplings/lib/python3.11/site-packages/evcouplings/align/tools.py", line 356, in run_jackhmmer
    return_code, stdout, stderr = run(cmd)
                                  ^^^^^^^^
  File "/users/blehner/mtopolska/miniconda3/envs/EVcouplings/lib/python3.11/site-packages/evcouplings/utils/system.py", line 74, in run
    raise ExternalToolError(
evcouplings.utils.system.ExternalToolError: Call failed:
cmd=['/users/project/prj004631/mtopolska/predictors/hmmer/hmmer-3.4/src/jackhmmer', '-N', '5', '-o', '/users/project/prj004631/mtopolska/predictors/EVcouplings/output/final_job_array/resubmitted_failed/2LYR/align/2LYR.output', '-A', '/users/project/prj004631/mtopolska/predictors/EVcouplings/output/final_job_array/resubmitted_failed/2LYR/align/2LYR.sto', '--tblout', '/users/project/prj004631/mtopolska/predictors/EVcouplings/output/final_job_array/resubmitted_failed/2LYR/align/2LYR.tblout', '--domtblout', '/users/project/prj004631/mtopolska/predictors/EVcouplings/output/final_job_array/resubmitted_failed/2LYR/align/2LYR.domtblout', '--noali', '--notextw', '-T', '31.0', '--domT', '31.0', '--incT', '31.0', '--incdomT', '31.0', '--cpu', '10', '/users/project/prj004631/mtopolska/predictors/EVcouplings/output/final_job_array/resubmitted_failed/2LYR/align/2LYR.fa', '/nfs/db/uniprot/2023_03/uniref/uniref100/blast/db/uniref100.fasta']
returncode=-9
stdout=
stderr=
2LYR.failed (END)
```

I cant really figure out what the issue might be, I would appreciate your insight. 
Best, 
Magda

**Comment by thomashopf** [comment]
Hi @mtopolska, are the alignment output files generated by jackhmmer for the failing runs very large by any chance? A common problem in the align stage is that hmmer runs out of memory (in the context of a compute cluster that typically means termination by the grid engine). Solution is to rerun and try more restrictive bitscore/e-value cutoffs - does that fix the issue for you?

**Comment by mtopolska** [comment]
Yes thanks a lot, that did it!
